CREATE TABLE IF NOT EXISTS public.sitemap (
    id SERIAL PRIMARY KEY,
    sitemap_url VARCHAR(255) NOT NULL UNIQUE,
    etag VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    size_mb FLOAT
);